<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PadelLeagueBundleEntityUserProxy extends \Padel\LeagueBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function getCreatedAt()
    {
        $this->_load();
        return parent::getCreatedAt();
    }

    public function getUsername()
    {
        $this->_load();
        return parent::getUsername();
    }

    public function setUsername($value)
    {
        $this->_load();
        return parent::setUsername($value);
    }

    public function getPassword()
    {
        $this->_load();
        return parent::getPassword();
    }

    public function setPassword($value)
    {
        $this->_load();
        return parent::setPassword($value);
    }

    public function getSalt()
    {
        $this->_load();
        return parent::getSalt();
    }

    public function setSalt($value)
    {
        $this->_load();
        return parent::setSalt($value);
    }

    public function getUserRoles()
    {
        $this->_load();
        return parent::getUserRoles();
    }

    public function eraseCredentials()
    {
        $this->_load();
        return parent::eraseCredentials();
    }

    public function getRoles()
    {
        $this->_load();
        return parent::getRoles();
    }

    public function equals(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        $this->_load();
        return parent::equals($user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'userRoles', 'id', 'createdAt', 'username', 'password', 'salt');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}