<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PadelLeagueBundleEntityStageProxy extends \Padel\LeagueBundle\Entity\Stage implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setNumber($number)
    {
        $this->_load();
        return parent::setNumber($number);
    }

    public function getNumber()
    {
        $this->_load();
        return parent::getNumber();
    }

    public function setStartDate($startDate)
    {
        $this->_load();
        return parent::setStartDate($startDate);
    }

    public function getStartDate()
    {
        $this->_load();
        return parent::getStartDate();
    }

    public function setFinishDate($finishDate)
    {
        $this->_load();
        return parent::setFinishDate($finishDate);
    }

    public function getFinishDate()
    {
        $this->_load();
        return parent::getFinishDate();
    }

    public function setYear($year)
    {
        $this->_load();
        return parent::setYear($year);
    }

    public function getYear()
    {
        $this->_load();
        return parent::getYear();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setLeague(\Padel\LeagueBundle\Entity\League $league)
    {
        $this->_load();
        return parent::setLeague($league);
    }

    public function getLeague()
    {
        $this->_load();
        return parent::getLeague();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'number', 'startDate', 'finishDate', 'year', 'status', 'league');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}